export default {
  START_GAME: 'START_GAME',
  SAVE_SCORE: 'SAVE_SCORE',
  GET_SCORES: 'GET_SCORES',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE'
};
